### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Elias-SLH** [sswapnil2/django-quiz-app#6]
I get this error 'NoneType' object is not iterable with this location django-quiz-app/mcq/models.py in get_answers_list, line 41. So the problem is that portion of code:
`def get_answers_list(self):
        return [(answer.id, answer.content) for answer in self.order_answers(Answer.objects.filter(question=self))]`
I dont know how to fix it and why is it returning a NoneType object.

**Comment by beremtl** [comment]
Hi. I have the same problem, can you tell me how you solved it?

**Comment by ropali** [comment]
Did anyone get the solution for this issue?

**Comment by crukundo** [comment]
Hey @Elias-SLH noticed you closed the issue, how did you resolve this? Just hit this block
